name: equatable_lint
version: 0.1.0
description: This is a set of rules to make classes using Equatable more maintainable. We make sure here that every fields in an Equatable class is linked to the Equatable props getter.
homepage: https://github.com/valentinmarq/equatable_lint
repository: https://github.com/valentinmarq/equatable_lint

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.10.0
  collection: ^1.16.0
  custom_lint_builder: ^0.0.12
  equatable: ^2.0.5
  source_gen: ^1.2.5

# dev_dependencies:
