name: Test Equatable Lint Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: dart-lang/setup-dart@v1.4

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib

      - name: Analyze
        run: dart analyze lib
